package cmd

import (
	"bufio"
	"fmt"
	"os"
	"strings"

	"github.com/mulgadc/spinifex/spinifex/admin"
	handlers_acm "github.com/mulgadc/spinifex/spinifex/handlers/acm"
	"github.com/spf13/cobra"
)

var certCreateTenantCACmd = &cobra.Command{
	Use:   "create-tenant-ca",
	Short: "Create the ACM tenant private CA for PRIVATE_CA certificate issuance",
	Long: `Creates the tenant root CA that ACM's PRIVATE_CA validation mode signs leaf
certificates from. This is a separate, independent root from the platform CA
(ca.pem/ca.key generated by 'spx admin init') — it is never used for node-to-node
trust, ipsec, or system VM guests, and installing it into device trust stores
is a one-time, per-deployment action.

--domain is required and repeatable. The domains given here are baked into the
CA as x509 name constraints and are frozen at creation: PRIVATE_CA certificate
requests are only honoured for these domains (and their subdomains), and
widening the list later requires regenerating the root.

Running this command against an already-existing tenant CA reports what is
already there rather than silently regenerating — rotating the root invalidates
every device's trust store at once, so that can only ever be an explicit,
operator-driven action via --regenerate.`,
	Run: runCertCreateTenantCA,
}

func init() {
	certCmd.AddCommand(certCreateTenantCACmd)
	certCreateTenantCACmd.Flags().StringSlice("domain", nil, "Domain the tenant CA is permitted to sign for (repeatable)")
	certCreateTenantCACmd.Flags().Bool("regenerate", false, "Replace an existing tenant CA with a fresh root (invalidates every device's trust store — requires confirmation)")
	certCreateTenantCACmd.Flags().Bool("yes", false, "Skip the --regenerate confirmation prompt")
	if err := certCreateTenantCACmd.MarkFlagRequired("domain"); err != nil {
		panic(err)
	}
}

func runCertCreateTenantCA(cmd *cobra.Command, _ []string) {
	domains, _ := cmd.Flags().GetStringSlice("domain")
	regenerate, _ := cmd.Flags().GetBool("regenerate")
	yes, _ := cmd.Flags().GetBool("yes")

	configDir, _ := cmd.Root().Flags().GetString("config-dir")
	certPath := admin.TenantCACertPath(configDir)
	keyPath := admin.TenantCAKeyPath(configDir)

	existed := admin.FileExists(certPath) && admin.FileExists(keyPath)

	if existed && regenerate {
		fmt.Println("⚠️  About to regenerate the tenant CA. This invalidates trust for every")
		fmt.Println("   device that has installed the current root — each one will need the new")
		fmt.Println("   certificate reinstalled before it trusts PRIVATE_CA leaves again.")
		fmt.Printf("   Current CA:      %s\n", certPath)
		fmt.Printf("   New domains:     %s\n", strings.Join(domains, ", "))
		fmt.Println()
		if !yes {
			fmt.Print("Type 'yes' to proceed: ")
			reader := bufio.NewReader(os.Stdin)
			answer, _ := reader.ReadString('\n')
			if strings.TrimSpace(answer) != "yes" {
				fmt.Println("Aborted.")
				return
			}
		}
		// Regeneration is a deliberate, explicit action only reachable via
		// --regenerate (plus confirmation) — LoadOrCreateTenantCA itself never
		// regenerates over an existing root, so the old files are removed first
		// to put it back on the "create" path.
		if err := os.Remove(certPath); err != nil {
			fmt.Fprintf(os.Stderr, "Error removing existing tenant CA cert: %v\n", err)
			os.Exit(1)
		}
		if err := os.Remove(keyPath); err != nil {
			fmt.Fprintf(os.Stderr, "Error removing existing tenant CA key: %v\n", err)
			os.Exit(1)
		}
	} else if existed {
		fmt.Println("Tenant CA already exists — reporting current state (use --regenerate to replace it):")
	}

	ca, err := handlers_acm.LoadOrCreateTenantCA(certPath, keyPath, domains)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}

	if existed && !regenerate {
		fmt.Println("✅ No changes made.")
	} else {
		fmt.Println("✅ Tenant CA ready.")
	}
	fmt.Printf("   Certificate:      %s\n", certPath)
	fmt.Printf("   Key:              %s (0600)\n", keyPath)
	fmt.Printf("   Permitted domains: %s\n", strings.Join(ca.PermittedDomains(), ", "))
	fmt.Println()
	fmt.Println("Install the certificate into every client's trust store so PRIVATE_CA")
	fmt.Println("certificates are trusted. The tenant CA is only loaded at daemon startup, so")
	fmt.Println("restart spinifex-daemon on any node that started before this CA existed:")
	fmt.Println("  sudo systemctl restart spinifex-daemon")
}
