package handlers_elbv2

import (
	"fmt"
	"log/slog"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"sync"
	"syscall"
	"text/template"
)

// Every interpolated string field in the templates below MUST be regex-validated
// at its input boundary. A newline or HAProxy keyword in any unvalidated field
// would inject arbitrary directives into the rendered config. The current
// surface is HealthCheckPath and HealthCheckMatcher (validated in
// CreateTargetGroup); all other interpolated identifiers go through
// sanitizeName or are integers.
const haproxyConfigTemplate = `# Auto-generated by spinifex ELBv2 — do not edit
global
    log stdout format short daemon
    stats socket {{.SocketPath}} mode 660 level admin

defaults
    mode http
    log global
    option httplog
    timeout connect 5s
    timeout client 60s
    timeout server 60s
{{range .Frontends}}
frontend {{.Name}}
    bind *:{{.Port}}
{{- range .Rules}}
{{- range .ACLs}}
    acl {{.Name}} {{.Expr}}
{{- end}}
    use_backend {{.Backend}} if{{range .ConditionNames}} {{.}}{{end}}
{{- end}}
    default_backend {{.DefaultBackend}}
{{end}}
{{range .Backends}}
backend {{.Name}}
    balance roundrobin{{if .HealthCheckPath}}
    option httpchk GET {{.HealthCheckPath}}
    http-check expect status {{.HealthCheckMatcher}}{{end}}
{{- range .Servers}}
    server {{.Name}} {{.Addr}}:{{.Port}} check inter {{.CheckInterval}}s fall {{.Fall}} rise {{.Rise}}
{{- end}}
{{end}}
`

const haproxyTCPConfigTemplate = `# Auto-generated by spinifex ELBv2 (NLB) — do not edit
global
    log stdout format short daemon
    stats socket {{.SocketPath}} mode 660 level admin

defaults
    mode tcp
    log global
    option tcplog
    timeout connect 5s
    timeout client 60s
    timeout server 60s
{{range .Frontends}}
frontend {{.Name}}
    bind *:{{.Port}}
    default_backend {{.DefaultBackend}}
{{end}}
{{range .Backends}}
backend {{.Name}}
    balance roundrobin
{{- if .TCPCheck}}
    option tcp-check
{{- end}}
{{- if .HTTPCheck}}
    option httpchk GET {{.HealthCheckPath}}
    http-check expect status {{.HealthCheckMatcher}}
{{- end}}
{{- range .Servers}}
    server {{.Name}} {{.Addr}}:{{.Port}} check inter {{.CheckInterval}}s fall {{.Fall}} rise {{.Rise}}
{{- end}}
{{end}}
`

var (
	haproxyHTTPTmpl = template.Must(template.New("haproxy").Parse(haproxyConfigTemplate))
	haproxyTCPTmpl  = template.Must(template.New("haproxy-tcp").Parse(haproxyTCPConfigTemplate))
)

// HAProxyConfig holds the full configuration for rendering the HAProxy template.
type HAProxyConfig struct {
	SocketPath string
	Frontends  []HAProxyFrontend
	Backends   []HAProxyBackend
}

// HAProxyFrontend represents a listener frontend.
type HAProxyFrontend struct {
	Name           string
	BindAddr       string
	Port           int64
	DefaultBackend string
	Rules          []HAProxyRule
}

// HAProxyRule represents one routing rule emitted as ACL declarations + a
// use_backend directive. Multiple ACLs sharing a Name are OR'd by HAProxy;
// distinct ConditionNames in the use_backend "if" clause are AND'd.
type HAProxyRule struct {
	Backend        string
	ACLs           []HAProxyACL
	ConditionNames []string
}

// HAProxyACL is one acl line. Name may repeat across the rule's ACL slice to
// express OR semantics over multiple match expressions.
type HAProxyACL struct {
	Name string
	Expr string
}

// HAProxyBackend represents a target group backend.
type HAProxyBackend struct {
	Name               string
	HealthCheckPath    string
	HealthCheckMatcher string
	TCPCheck           bool
	HTTPCheck          bool
	Servers            []HAProxyServer
}

// HAProxyServer represents a single target server.
type HAProxyServer struct {
	Name          string
	Addr          string
	Port          int64
	CheckInterval int64
	Fall          int64
	Rise          int64
}

// GenerateHAProxyConfig builds an HAProxy config string from the LB, its
// listeners, target groups, and per-listener rules. For NLBs it generates a
// TCP-mode config and ignores rules (NLB has no L7 routing).
func GenerateHAProxyConfig(lb *LoadBalancerRecord, listeners []*ListenerRecord, tgByArn map[string]*TargetGroupRecord, rulesByListener map[string][]*RuleRecord, bindAddr string) (string, error) {
	if lb.Type == LoadBalancerTypeNetwork {
		return generateNLBConfig(lb, listeners, tgByArn, bindAddr)
	}
	return generateALBConfig(lb, listeners, tgByArn, rulesByListener, bindAddr)
}

// generateALBConfig builds an HTTP-mode HAProxy config for ALBs.
func generateALBConfig(lb *LoadBalancerRecord, listeners []*ListenerRecord, tgByArn map[string]*TargetGroupRecord, rulesByListener map[string][]*RuleRecord, bindAddr string) (string, error) {
	cfg, err := buildHAProxyConfig(lb, listeners, tgByArn, rulesByListener, bindAddr, false)
	if err != nil {
		return "", err
	}

	var buf strings.Builder
	if err := haproxyHTTPTmpl.Execute(&buf, cfg); err != nil {
		return "", fmt.Errorf("execute haproxy template: %w", err)
	}

	return buf.String(), nil
}

// generateNLBConfig builds a TCP-mode HAProxy config for NLBs.
func generateNLBConfig(lb *LoadBalancerRecord, listeners []*ListenerRecord, tgByArn map[string]*TargetGroupRecord, bindAddr string) (string, error) {
	cfg, err := buildHAProxyConfig(lb, listeners, tgByArn, nil, bindAddr, true)
	if err != nil {
		return "", err
	}

	var buf strings.Builder
	if err := haproxyTCPTmpl.Execute(&buf, cfg); err != nil {
		return "", fmt.Errorf("execute haproxy tcp template: %w", err)
	}

	return buf.String(), nil
}

// buildHAProxyConfig constructs the HAProxyConfig struct shared by ALB and NLB
// generation. For ALBs, rulesByListener provides per-listener rules sorted by
// priority; nil/empty for NLBs.
func buildHAProxyConfig(lb *LoadBalancerRecord, listeners []*ListenerRecord, tgByArn map[string]*TargetGroupRecord, rulesByListener map[string][]*RuleRecord, bindAddr string, isTCP bool) (HAProxyConfig, error) {
	socketDir := filepath.Join(os.TempDir(), "spinifex-haproxy")
	// Use "lb" prefix for both ALB and NLB — must match the agent's socket path.
	socketPath := filepath.Join(socketDir, fmt.Sprintf("lb-%s.sock", lb.LoadBalancerID))

	cfg := HAProxyConfig{
		SocketPath: socketPath,
	}
	backendAdded := make(map[string]struct{})

	addBackend := func(tgArn string) {
		backendName := sanitizeName("bk", tgArn)
		if _, ok := backendAdded[backendName]; ok {
			return
		}
		tg, ok := tgByArn[tgArn]
		if !ok {
			return
		}

		backend := HAProxyBackend{Name: backendName}
		if isTCP {
			switch tg.HealthCheck.Protocol {
			case ProtocolHTTP, ProtocolHTTPS:
				backend.HTTPCheck = true
				backend.HealthCheckPath = tg.HealthCheck.Path
				backend.HealthCheckMatcher = tg.HealthCheck.Matcher
			default:
				backend.TCPCheck = true
			}
		} else {
			backend.HealthCheckPath = tg.HealthCheck.Path
			backend.HealthCheckMatcher = tg.HealthCheck.Matcher
		}

		for _, target := range tg.Targets {
			if target.PrivateIP == "" || target.HealthState == TargetHealthDraining {
				continue
			}
			backend.Servers = append(backend.Servers, HAProxyServer{
				Name:          sanitizeName("srv", target.Id),
				Addr:          target.PrivateIP,
				Port:          target.Port,
				CheckInterval: tg.HealthCheck.IntervalSeconds,
				Fall:          tg.HealthCheck.UnhealthyThreshold,
				Rise:          tg.HealthCheck.HealthyThreshold,
			})
		}
		cfg.Backends = append(cfg.Backends, backend)
		backendAdded[backendName] = struct{}{}
	}

	for _, l := range listeners {
		if len(l.DefaultActions) == 0 {
			continue
		}

		tgArn := l.DefaultActions[0].TargetGroupArn
		defaultBackendName := sanitizeName("bk", tgArn)

		frontend := HAProxyFrontend{
			Name:           sanitizeName("ft", l.ListenerArn),
			BindAddr:       bindAddr,
			Port:           l.Port,
			DefaultBackend: defaultBackendName,
		}

		if !isTCP {
			rules := rulesByListener[l.ListenerArn]
			for _, r := range rules {
				rule, err := buildHAProxyRule(r)
				if err != nil {
					return HAProxyConfig{}, err
				}
				frontend.Rules = append(frontend.Rules, rule)
				for _, a := range r.Actions {
					if a.Type == ActionTypeForward && a.TargetGroupArn != "" {
						addBackend(a.TargetGroupArn)
					}
				}
			}
		}

		cfg.Frontends = append(cfg.Frontends, frontend)
		addBackend(tgArn)
	}

	return cfg, nil
}

// buildHAProxyRule converts a RuleRecord into the rendered ACL+use_backend
// shape. Returns an error if any condition value fails the defence-in-depth
// re-validation (HAProxy meta-character rejection).
func buildHAProxyRule(r *RuleRecord) (HAProxyRule, error) {
	if len(r.Actions) == 0 || r.Actions[0].Type != ActionTypeForward {
		return HAProxyRule{}, fmt.Errorf("rule %s has no forward action", r.RuleID)
	}

	rule := HAProxyRule{Backend: sanitizeName("bk", r.Actions[0].TargetGroupArn)}

	for ci, c := range r.Conditions {
		aclName := fmt.Sprintf("r%s_c%d", sanitizeACLToken(r.RuleID), ci)
		exprs, err := buildHAProxyACLExprs(c)
		if err != nil {
			return HAProxyRule{}, fmt.Errorf("rule %s condition %d: %w", r.RuleID, ci, err)
		}
		for _, e := range exprs {
			rule.ACLs = append(rule.ACLs, HAProxyACL{Name: aclName, Expr: e})
		}
		rule.ConditionNames = append(rule.ConditionNames, aclName)
	}

	return rule, nil
}

// buildHAProxyACLExprs returns one or more HAProxy ACL expressions for a
// single rule condition. Multiple expressions represent OR semantics over the
// condition's values (HAProxy ORs same-name ACL declarations).
func buildHAProxyACLExprs(c RuleCondition) ([]string, error) {
	switch c.Field {
	case RuleFieldHostHeader:
		return hostOrPathExprs("hdr(host) -i", c.Values)
	case RuleFieldPathPattern:
		return hostOrPathExprs("path", c.Values)
	case RuleFieldHTTPHeader:
		if err := validateRenderSafe(c.HTTPHeaderName); err != nil {
			return nil, err
		}
		out := make([]string, 0, len(c.Values))
		for _, v := range c.Values {
			if err := validateRenderSafe(v); err != nil {
				return nil, err
			}
			out = append(out, fmt.Sprintf("hdr(%s) -i -m str %s", c.HTTPHeaderName, v))
		}
		return out, nil
	case RuleFieldHTTPRequestMethod:
		out := make([]string, 0, len(c.Values))
		for _, v := range c.Values {
			if err := validateRenderSafe(v); err != nil {
				return nil, err
			}
			out = append(out, fmt.Sprintf("method %s", v))
		}
		return out, nil
	case RuleFieldQueryString:
		out := make([]string, 0, len(c.QueryStringKVs))
		for _, kv := range c.QueryStringKVs {
			if err := validateRenderSafe(kv.Value); err != nil {
				return nil, err
			}
			if kv.Key == "" {
				out = append(out, fmt.Sprintf("url_sub %s", kv.Value))
				continue
			}
			if err := validateRenderSafe(kv.Key); err != nil {
				return nil, err
			}
			out = append(out, fmt.Sprintf("urlp(%s) -m str %s", kv.Key, kv.Value))
		}
		return out, nil
	case RuleFieldSourceIP:
		out := make([]string, 0, len(c.Values))
		for _, v := range c.Values {
			if err := validateRenderSafe(v); err != nil {
				return nil, err
			}
			out = append(out, fmt.Sprintf("src %s", v))
		}
		return out, nil
	default:
		return nil, fmt.Errorf("unsupported rule field %q", c.Field)
	}
}

func hostOrPathExprs(prefix string, values []string) ([]string, error) {
	out := make([]string, 0, len(values))
	for _, v := range values {
		if err := validateRenderSafe(v); err != nil {
			return nil, err
		}
		flag, lit := wildcardMatch(v)
		out = append(out, fmt.Sprintf("%s -m %s %s", prefix, flag, lit))
	}
	return out, nil
}

// wildcardMatch maps a host/path pattern to a HAProxy match flag + literal.
// Supports leading *, trailing *, or no wildcard. Embedded `?` or interior `*`
// fall through to substring match (`sub`) — AWS treats `?` as single-char
// wildcard; HAProxy lacks an exact equivalent so we widen to substring (false
// positives over false negatives is the right failure mode for a router).
func wildcardMatch(v string) (flag, literal string) {
	hasLead := strings.HasPrefix(v, "*")
	hasTrail := strings.HasSuffix(v, "*")
	switch {
	case hasLead && hasTrail && len(v) > 2:
		return "sub", v[1 : len(v)-1]
	case hasLead && len(v) > 1:
		return "end", v[1:]
	case hasTrail && len(v) > 1:
		return "beg", v[:len(v)-1]
	case strings.ContainsAny(v, "*?"):
		return "sub", strings.Trim(v, "*?")
	default:
		return "str", v
	}
}

// validateRenderSafe rejects bytes that could break ACL parsing or inject new
// directives. Mirrors the write-time validators in service_impl_rules.go;
// duplicated here so a future migration that bypasses the API cannot leak a
// malicious string into the generated config.
func validateRenderSafe(v string) error {
	if v == "" {
		return fmt.Errorf("empty rule token")
	}
	for _, r := range v {
		if r == '\n' || r == '\r' || r == '#' || r == '"' || r == ' ' || r == '\t' {
			return fmt.Errorf("rule token contains forbidden character %q", r)
		}
	}
	return nil
}

// sanitizeACLToken trims an identifier to safe HAProxy ACL-name characters.
func sanitizeACLToken(id string) string {
	var sb strings.Builder
	for _, c := range id {
		if (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') {
			sb.WriteRune(c)
		}
	}
	return sb.String()
}

// sanitizeName creates a safe identifier from an ARN or ID for use in HAProxy config.
func sanitizeName(prefix, id string) string {
	// Use last segment of ARN or ID, replace non-alphanumeric with underscore
	parts := strings.Split(id, "/")
	name := parts[len(parts)-1]
	var sb strings.Builder
	for _, c := range name {
		if (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '-' || c == '_' {
			sb.WriteRune(c)
		} else {
			sb.WriteRune('_')
		}
	}
	return prefix + "_" + sb.String()
}

// HAProxyManager manages HAProxy processes for ALBs on this daemon node.
type HAProxyManager struct {
	configDir string // Directory for HAProxy config files
	binPath   string // Path to haproxy binary
	mu        sync.Mutex
	pids      map[string]int // lbID → HAProxy PID
}

// NewHAProxyManager creates a new HAProxy manager.
func NewHAProxyManager(configDir string) *HAProxyManager {
	binPath := "/usr/sbin/haproxy"
	if p, err := exec.LookPath("haproxy"); err == nil {
		binPath = p
	}
	return &HAProxyManager{
		configDir: configDir,
		binPath:   binPath,
		pids:      make(map[string]int),
	}
}

// Available returns true if the haproxy binary is found on the system.
func (m *HAProxyManager) Available() bool {
	_, err := exec.LookPath(m.binPath)
	if err != nil {
		// binPath might be absolute — check directly
		_, err = os.Stat(m.binPath)
	}
	return err == nil
}

// pidFilePath returns the pidfile path for a given LB.
func (m *HAProxyManager) pidFilePath(lbID string) string {
	return filepath.Join(m.configDir, fmt.Sprintf("alb-%s.pid", lbID))
}

// configFilePath returns the config path for a given LB.
func (m *HAProxyManager) configFilePath(lbID string) string {
	return filepath.Join(m.configDir, fmt.Sprintf("alb-%s.cfg", lbID))
}

// IsRunning returns true if an HAProxy process is tracked and alive for this LB.
func (m *HAProxyManager) IsRunning(lbID string) bool {
	m.mu.Lock()
	pid, ok := m.pids[lbID]
	m.mu.Unlock()
	if !ok || pid <= 0 {
		return false
	}
	// Check if process is alive
	proc, err := os.FindProcess(pid)
	if err != nil {
		return false
	}
	return proc.Signal(syscall.Signal(0)) == nil
}

// Start launches a new HAProxy process for the given LB.
func (m *HAProxyManager) Start(lbID string) error {
	m.mu.Lock()
	defer m.mu.Unlock()

	return m.startLocked(lbID)
}

// startLocked is the lock-free core of Start. Caller must hold m.mu.
func (m *HAProxyManager) startLocked(lbID string) error {
	if err := os.MkdirAll(m.configDir, 0o750); err != nil {
		return fmt.Errorf("create config dir: %w", err)
	}

	// Ensure the stats socket directory exists
	socketDir := filepath.Join(os.TempDir(), "spinifex-haproxy")
	if err := os.MkdirAll(socketDir, 0o750); err != nil {
		return fmt.Errorf("create socket dir: %w", err)
	}

	configPath := m.configFilePath(lbID)
	pidFile := m.pidFilePath(lbID)

	cmd := exec.Command(m.binPath, "-f", configPath, "-p", pidFile, "-D")
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("haproxy start failed: %s: %w", strings.TrimSpace(string(output)), err)
	}

	// Read PID from pidfile
	pid, err := m.readPidFile(pidFile)
	if err != nil {
		slog.Warn("HAProxy started but could not read pidfile", "lbId", lbID, "err", err)
		return nil
	}

	m.pids[lbID] = pid
	slog.Info("HAProxy started", "lbId", lbID, "pid", pid)
	return nil
}

// Reload performs a graceful reload of the HAProxy process for the given LB.
// The old workers finish in-flight connections while new workers start.
func (m *HAProxyManager) Reload(lbID string) error {
	m.mu.Lock()
	defer m.mu.Unlock()

	oldPid, ok := m.pids[lbID]
	if !ok || oldPid <= 0 {
		// Not running — do a fresh start instead
		return m.startLocked(lbID)
	}

	configPath := m.configFilePath(lbID)
	pidFile := m.pidFilePath(lbID)

	cmd := exec.Command(m.binPath, "-f", configPath, "-p", pidFile, "-D", "-sf", strconv.Itoa(oldPid))
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("haproxy reload failed: %s: %w", strings.TrimSpace(string(output)), err)
	}

	// Read new PID
	newPid, err := m.readPidFile(pidFile)
	if err != nil {
		slog.Warn("HAProxy reloaded but could not read new pidfile", "lbId", lbID, "err", err)
		return nil
	}

	m.pids[lbID] = newPid
	slog.Info("HAProxy reloaded", "lbId", lbID, "oldPid", oldPid, "newPid", newPid)
	return nil
}

// Stop terminates the HAProxy process for the given LB and cleans up files.
func (m *HAProxyManager) Stop(lbID string) error {
	m.mu.Lock()
	defer m.mu.Unlock()

	pid, ok := m.pids[lbID]
	if ok && pid > 0 {
		proc, err := os.FindProcess(pid)
		if err == nil {
			if err := proc.Signal(syscall.SIGTERM); err != nil {
				slog.Debug("HAProxy SIGTERM failed (may already be stopped)", "lbId", lbID, "pid", pid, "err", err)
			}
		}
	}
	delete(m.pids, lbID)

	// Clean up pidfile
	pidFile := m.pidFilePath(lbID)
	os.Remove(pidFile)

	slog.Info("HAProxy stopped", "lbId", lbID, "pid", pid)
	return nil
}

// StopAll terminates all tracked HAProxy processes. Called on daemon shutdown.
func (m *HAProxyManager) StopAll() {
	m.mu.Lock()
	lbIDs := make([]string, 0, len(m.pids))
	for id := range m.pids {
		lbIDs = append(lbIDs, id)
	}
	m.mu.Unlock()

	for _, id := range lbIDs {
		if err := m.Stop(id); err != nil {
			slog.Warn("Failed to stop HAProxy on shutdown", "lbId", id, "err", err)
		}
	}
}

// readPidFile reads and parses a PID from a pidfile.
func (m *HAProxyManager) readPidFile(path string) (int, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return 0, err
	}
	pid, err := strconv.Atoi(strings.TrimSpace(string(data)))
	if err != nil {
		return 0, fmt.Errorf("parse pid %q: %w", string(data), err)
	}
	return pid, nil
}

// WriteConfig writes an HAProxy config file for the given load balancer.
func (m *HAProxyManager) WriteConfig(lbID, configContent string) (string, error) {
	if err := os.MkdirAll(m.configDir, 0o750); err != nil {
		return "", fmt.Errorf("create config dir: %w", err)
	}

	path := filepath.Join(m.configDir, fmt.Sprintf("alb-%s.cfg", lbID))
	if err := os.WriteFile(path, []byte(configContent), 0o600); err != nil {
		return "", fmt.Errorf("write haproxy config: %w", err)
	}

	slog.Info("Wrote HAProxy config", "path", path, "lbId", lbID)
	return path, nil
}

// RemoveConfig removes the HAProxy config file for the given load balancer.
func (m *HAProxyManager) RemoveConfig(lbID string) error {
	path := filepath.Join(m.configDir, fmt.Sprintf("alb-%s.cfg", lbID))
	if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("remove haproxy config: %w", err)
	}
	return nil
}

// ValidateConfig checks if an HAProxy config file is syntactically valid.
func (m *HAProxyManager) ValidateConfig(configPath string) error {
	cmd := exec.Command(m.binPath, "-c", "-f", configPath)
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("haproxy config validation failed: %s: %w", string(output), err)
	}
	return nil
}
