package handlers_elbv2

import (
	"fmt"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/mulgadc/spinifex/spinifex/lbagent"
)

// NLB (L4) data plane. HAProxy load-balances no UDP in any release, so NLB
// listeners (TCP/UDP/TLS/TCP_UDP) render an nginx `stream` config instead;
// ALBs stay on HAProxy. See docs/development/feature/nlb-nginx-l4-dataplane.md.
//
// Health checks are passive only (max_fails / fail_timeout) — OSS nginx stream
// has no active upstream probing.

const nginxStreamConfigTemplate = `# Auto-generated by spinifex ELBv2 (NLB) — do not edit
user root;
worker_processes auto;
error_log stderr;
pid {{.PIDPath}};

events {
    worker_connections 1024;
}

stream {
{{- range .Upstreams}}
    upstream {{.Name}} {
{{- range .Servers}}
        server {{.Addr}}:{{.Port}} max_fails={{.MaxFails}} fail_timeout={{.FailTimeout}}s;
{{- else}}
        server 127.0.0.1:1 down;
{{- end}}
    }
{{end}}
{{- range .Servers}}
    server {
        listen {{.Port}}{{if .UDP}} udp{{end}}{{if .SSL}} ssl{{end}};
{{- if .SSL}}
        ssl_certificate {{.CertPath}};
        ssl_certificate_key {{.CertPath}};
{{- end}}
{{- if .UDP}}
        proxy_responses 1;
        proxy_timeout 10s;
{{- end}}
        proxy_pass {{.Upstream}};
    }
{{end}}}
`

var nginxStreamTmpl = template.Must(
	template.New("nginx-stream").Parse(nginxStreamConfigTemplate),
)

// nginxConfig is the render model for the NLB nginx `stream` config.
type nginxConfig struct {
	PIDPath   string
	Upstreams []nginxUpstream
	Servers   []nginxServer
}

// nginxUpstream is one target group's backend pool. An empty pool renders a
// single permanently-down placeholder so nginx (which requires >=1 server)
// still validates.
type nginxUpstream struct {
	Name    string
	Servers []nginxUpstreamServer
}

type nginxUpstreamServer struct {
	Addr        string
	Port        int64
	MaxFails    int64
	FailTimeout int64
}

// nginxServer is one listener's `server` block. TCP_UDP listeners expand to two
// blocks on the same port (one TCP, one UDP).
type nginxServer struct {
	Port     int64
	UDP      bool
	SSL      bool
	CertPath string
	Upstream string
}

// engineForType reports the data-plane engine for a load balancer type: nginx
// for NLBs (L4), HAProxy for everything else (ALB / L7).
func engineForType(lbType string) string {
	if lbType == LoadBalancerTypeNetwork {
		return EngineNginx
	}
	return EngineHAProxy
}

// generateNLBStreamConfig builds an nginx `stream` config for an NLB. Secure
// (TLS) listeners terminate TLS at nginx and forward plaintext to the target;
// the returned certFiles map carries each cert path → combined PEM for delivery
// to the LB agent. bindAddr is unused (nginx listens on all addresses, matching
// the HAProxy `bind *` behaviour).
func generateNLBStreamConfig(lb *LoadBalancerRecord, listeners []*ListenerRecord, tgByArn map[string]*TargetGroupRecord, _ string, certPEMByArn map[string]string) (string, map[string]string, error) {
	cfg := nginxConfig{PIDPath: lbagent.NginxPIDPath}
	var certFiles map[string]string
	upstreamAdded := make(map[string]struct{})

	addUpstream := func(tgArn string) string {
		name := sanitizeName("us", tgArn)
		if _, ok := upstreamAdded[name]; ok {
			return name
		}
		us := nginxUpstream{Name: name}
		if tg, ok := tgByArn[tgArn]; ok {
			for _, t := range tg.Targets {
				if t.PrivateIP == "" || t.HealthState == TargetHealthDraining {
					continue
				}
				us.Servers = append(us.Servers, nginxUpstreamServer{
					Addr:        t.PrivateIP,
					Port:        t.Port,
					MaxFails:    tg.HealthCheck.UnhealthyThreshold,
					FailTimeout: tg.HealthCheck.IntervalSeconds,
				})
			}
		}
		cfg.Upstreams = append(cfg.Upstreams, us)
		upstreamAdded[name] = struct{}{}
		return name
	}

	for _, l := range listeners {
		if len(l.DefaultActions) == 0 {
			continue
		}
		da := l.DefaultActions[0]
		// NLB default actions are forward-only (no redirect / fixed-response).
		if da.Type != ActionTypeForward || da.TargetGroupArn == "" {
			continue
		}
		upstream := addUpstream(da.TargetGroupArn)

		var certPath string
		if protocolRequiresCert(l.Protocol) {
			pem, _ := resolveFrontendCert(lb, l, certPEMByArn)
			if pem != "" {
				certPath = nginxCertPath(lb, l)
				if certFiles == nil {
					certFiles = make(map[string]string)
				}
				certFiles[certPath] = pem
			}
		}

		switch l.Protocol {
		case ProtocolUDP:
			cfg.Servers = append(cfg.Servers, nginxServer{Port: l.Port, UDP: true, Upstream: upstream})
		case ProtocolTCPUDP:
			cfg.Servers = append(cfg.Servers,
				nginxServer{Port: l.Port, Upstream: upstream},
				nginxServer{Port: l.Port, UDP: true, Upstream: upstream})
		default: // TCP, TLS
			cfg.Servers = append(cfg.Servers, nginxServer{
				Port:     l.Port,
				SSL:      certPath != "",
				CertPath: certPath,
				Upstream: upstream,
			})
		}
	}

	var buf strings.Builder
	if err := nginxStreamTmpl.Execute(&buf, cfg); err != nil {
		return "", nil, fmt.Errorf("execute nginx stream template: %w", err)
	}
	return buf.String(), certFiles, nil
}

// nginxCertPath is the stable absolute PEM path for a TLS listener under the
// agent's nginx cert dir. Daemon-rendered and agent-written paths must match.
func nginxCertPath(lb *LoadBalancerRecord, l *ListenerRecord) string {
	return filepath.Join(lbagent.NginxCertDir, fmt.Sprintf("lb-%s-%s.pem", lb.LoadBalancerID, l.ListenerID))
}
