// Code generated by scripts/sync-aws-models.sh. DO NOT EDIT.

package awsmodel

// ModelCommit is the github.com/aws/api-models-aws commit the embedded
// models were taken from, and ModelCommitDate the day it was committed.
const (
	ModelCommit     = "9b1a4929274443d8671ea8acfda7afbe856e29e9"
	ModelCommitDate = "2026-09-25"
)
